name: esp32_dht_http
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^23.1.40
  http: ^1.1.0
  intl: ^0.18.1
  syncfusion_flutter_gauges: ^23.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
